services:
 
  db:
    image: "postgres"
    ports:
      - 5432:5432
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 5

  migrate:
    image: "migrate/migrate"
    volumes:
      - ./migrations:/migrations
    depends_on:
      db:
        condition: service_healthy
    command: ["-source", "file:///migrations", "-database", "postgres://postgres:postgres@db:5432/postgres?sslmode=disable", "up"]

  api:
    build: .
    depends_on:
      - migrate
    ports:
      - 8080:8080
    command: ["go", "run" , "cmd/sampleapp/main.go"]

  api-test:
    build: .
    depends_on:
      - migrate
    ports:
      - 8080:8080
    command: ["go", "test" , "-v", "./..."]
